export const SHOW_FORM_PROJECT = 'SHOW_FORM_PROJECT';
export const HIDE_FORM_PROJECT = 'HIDE_FORM_PROJECT';
export const GET_PROJECTS = 'GET_PROJECTS';
export const ADD_NEW_PROJECT = 'ADD_NEW_PROJECT';
export const VALIDATE_FORM = 'VARIDATE_FORM';
export const CURRENT_PROJECT = 'CURRENT_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';