export const GET_TASKS_PROJECT = 'GET_TASKS_PROJECT';
export const ADD_TASK_PROJECT = 'ADD_TASK_PROJECT';
export const VALIDATE_FORM = 'VALIDATE_FORM';
export const DELETE_TASK = 'DELETE_TASK';
export const UPDATE_TASK_STATUS = 'UPDATE_TASK_STATUS';